CREATE TABLE user (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, position_id INTEGER NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, description CLOB DEFAULT NULL, is_record_active BOOLEAN NOT NULL, position VARCHAR(255) NOT NULL);
CREATE INDEX IDX_8D93D649DD842E46 ON user (position_id);
CREATE TABLE developer (id INTEGER NOT NULL, ide_environments VARCHAR(255) DEFAULT NULL, programing_languages VARCHAR(255) DEFAULT NULL, is_sql BOOLEAN DEFAULT NULL, PRIMARY KEY(id));
CREATE TABLE tester (id INTEGER NOT NULL, test_systems VARCHAR(255) DEFAULT NULL, report_systems VARCHAR(255) DEFAULT NULL, is_selenium BOOLEAN DEFAULT NULL, PRIMARY KEY(id));
CREATE TABLE position (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(255) NOT NULL, is_record_active BOOLEAN NOT NULL);
CREATE TABLE project_manager (id INTEGER NOT NULL, project_methodology VARCHAR(255) DEFAULT NULL, report_systems VARCHAR(255) DEFAULT NULL, is_scrum BOOLEAN DEFAULT NULL, PRIMARY KEY(id));
